@testable import HTMLKit
import XCTest

final class ElementTests: XCTestCase {
    
    /// Tests the correct syntax for the content nodes.
    func testContentNodeSyntax() throws {
        
        let names: [String] = [
            "head",
            "title",
            "style",
            "html",
            "body",
            "article",
            "section",
            "nav",
            "aside",
            "h1",
            "h2",
            "h3",
            "h4",
            "h5",
            "h6",
            "hgroup",
            "header",
            "footer",
            "address",
            "p",
            "pre",
            "blockquote",
            "ol",
            "ul",
            "menu",
            "li",
            "dl",
            "dt",
            "dd",
            "figure",
            "figcaption",
            "main",
            "search",
            "a",
            "em",
            "strong",
            "small",
            "s",
            "cite",
            "q",
            "dfn",
            "abbr",
            "ruby",
            "rt",
            "rp",
            "data",
            "time",
            "code",
            "var",
            "samp",
            "kbd",
            "sub",
            "sup",
            "i",
            "b",
            "u",
            "mark",
            "bdi",
            "span",
            "ins",
            "del",
            "picture",
            "iframe",
            "object",
            "video",
            "audio",
            "map",
            "table",
            "caption",
            "colgroup",
            "tbody",
            "thead",
            "tfoot",
            "tr",
            "td",
            "th",
            "form",
            "label",
            "button",
            "datalist",
            "optgroup",
            "option",
            "textarea",
            "output",
            "progress",
            "meter",
            "fieldset",
            "legend",
            "details",
            "summary",
            "dialog",
            "script",
            "noscript",
            "template",
            "canvas",
            "svg",
            "circle",
            "rect",
            "ellipse",
            "line",
            "polygon",
            "polyline",
            "path",
            "use",
            "slot"
        ]
        
        let nodes: [any ContentNode] = [
            Head(), 
            Title(),
            Style(),
            Html(),
            Body(),
            Article(),
            Section(),
            Navigation(),
            Aside(),
            Heading1(),
            Heading2(),
            Heading3(),
            Heading4(),
            Heading5(),
            Heading6(),
            HeadingGroup(),
            Header(),
            Footer(),
            Address(),
            Paragraph(),
            PreformattedText(),
            Blockquote(),
            OrderedList(),
            UnorderedList(),
            Menu(),
            ListItem(),
            DescriptionList(),
            TermName(),
            TermDefinition(),
            Figure(),
            FigureCaption(),
            Main(),
            Search(),
            Anchor(),
            Emphasize(),
            Strong(),
            Small(),
            StrikeThrough(),
            Cite(),
            ShortQuote(),
            Definition(),
            Abbreviation(),
            Ruby(),
            RubyText(),
            RubyPronunciation(),
            Data(),
            Time(),
            Code(),
            Variable(),
            SampleOutput(),
            KeyboardInput(),
            Subscript(),
            Superscript(),
            Italic(),
            Bold(),
            Underline(),
            Mark(),
            Bdi(),
            Span(),
            InsertedText(),
            DeletedText(),
            Picture(),
            InlineFrame(),
            Object(),
            Video(),
            Audio(),
            Map(),
            Table(),
            Caption(),
            ColumnGroup(),
            TableBody(),
            TableHead(),
            TableFoot(),
            TableRow(),
            DataCell(),
            HeaderCell(),
            Form(),
            Label(),
            Button(),
            DataList(),
            OptionGroup(),
            Option(),
            TextArea(),
            Output(),
            Progress(),
            Meter(),
            Fieldset(),
            Legend(),
            Details(),
            Summary(),
            Dialog(),
            Script(),
            NoScript(),
            Template(),
            Canvas(),
            Vector(),
            Circle(),
            Rectangle(),
            Ellipse(),
            Line(),
            Polygon(),
            Polyline(),
            Path(),
            Use(),
            Slot()
        ]
        
        for (index, node) in nodes.enumerated() {
            XCTAssertEqual(node.name, names[index])
        }
    }
    
    /// Tests the correct syntax for the empty nodes.
    func testEmptyNodeSyntax() throws {
        
        let names: [String] = [
            "base",
            "link",
            "meta",
            "hr",
            "bdo",
            "br",
            "wbr",
            "source",
            "img",
            "embed",
            "track",
            "area",
            "col",
            "input"
        ]
        
        let nodes: [any EmptyNode] = [
            Base(),
            Link(),
            Meta(),
            HorizontalRule(),
            Bdo(),
            LineBreak(),
            WordBreak(),
            Source(),
            Image(),
            Embed(),
            Track(),
            Area(),
            Column(),
            Input()
        ]
        
        for (index, node) in nodes.enumerated() {
            XCTAssertEqual(node.name, names[index])
        }
    }
    
    /// Tests whether the typealias references the correct underlying type.
    func testContentNodeAlias() throws {
        
        let names: [String] = [
            "nav",
            "h1",
            "h2",
            "h3",
            "h4",
            "h5",
            "h6",
            "hgroup",
            "p",
            "pre",
            "ol",
            "ul",
            "li",
            "dl",
            "dt",
            "dd",
            "figcaption",
            "a",
            "em",
            "s",
            "q",
            "dfn",
            "abbr",
            "rt",
            "rp",
            "var",
            "samp",
            "kbd",
            "sub",
            "sup",
            "i",
            "b",
            "u",
            "ins",
            "del",
            "iframe",
            "colgroup",
            "tbody",
            "thead",
            "tfoot",
            "tr",
            "td",
            "th",
            "optgroup",
            "svg",
            "rect"
        ]
        
        let nodes: [any ContentNode] = [
            Nav(),
            H1(),
            H2(),
            H3(),
            H4(),
            H5(),
            H6(),
            Hgroup(),
            P(),
            Pre(),
            Ol(),
            Ul(),
            Li(),
            Dl(),
            Dt(),
            Dd(),
            Figcaption(),
            A(),
            Em(),
            S(),
            Q(),
            Dfn(),
            Abbr(),
            Rt(),
            Rp(),
            Var(),
            Samp(),
            Kbd(),
            Sub(),
            Sup(),
            I(),
            B(),
            U(),
            Ins(),
            Del(),
            Iframe(),
            Colgroup(),
            Tbody(),
            Thead(),
            Tfoot(),
            Tr(),
            Td(),
            Th(),
            Optgroup(),
            Svg(),
            Rect()
        ]
        
        for (index, node) in nodes.enumerated() {
            XCTAssertEqual(node.name, names[index])
        }
    }
    
    /// Tests whether the typealias references the correct underlying type.
    func testEmptyNodeAlias() throws {
        
        let names: [String] = [
            "hr",
            "br",
            "wbr",
            "img",
            "col"
        ]
        
        let nodes: [any EmptyNode] = [
            Hr(),
            Br(),
            Wbr(),
            Img(),
            Col()
        ]
        
        for (index, node) in nodes.enumerated() {
            XCTAssertEqual(node.name, names[index])
        }
    }
}
