name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  test-pushpull:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ "swift:6.0.3-jammy", "swift:6.0.3-noble" ]
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run tests
        run: swift test
